### ISSUE TITLE
依存ライブラリについての明記がない

### ISSUE THREAD

**Issue by LWisteria** [fixstars/sacana#18]
手元のUbuntu 20.10のまっさらな状態からビルドしたところ

* build-essential
* libssl-dev

が必要でした。依存ライブラリがあることについては明記したほうが良いようにも思います（ただしこれはcrateで持ってきたライブラリが依存しているとも言えるので、ここのREADMEに書くべきなのかは判断迷うところですね

**Comment by toru-fukaya** [comment]
調べてみた所、依存で言うと `sacana->reqwest->hyper-tls->native-tls->openssl-sys` がcc、pkg-config、opensslを必要としているので、Ubuntuだと上記のものが必要になるようです。

自分が直接依存してなくても書いている例があったので ( https://crates.io/crates/cargo-tree ) 書いた方が親切かなと思います。

書くとした場合、直接依存パッケージを書くのではなくhttps://docs.rs/openssl/#automatic へのリンクを張る方が良いかもしれません。(色んなディストリビューションの例が書いてありますし、良くメンテナンスされていると思うので)

**Comment by toru-fukaya** [comment]
結論としては書いてある方が良いと思うので、(今すぐではありませんが)書く予定です。

**Comment by toru-fukaya** [comment]
#21 がマージされたので閉じます
