### ISSUE TITLE
チャンネル情報の取得をオンデマンドにする

### ISSUE THREAD

**Issue by vorj** [fixstars/sacana#27]
- チャンネル数が大量にあるワークスペースで複数のbotを起動しようとすると `conversations.list` のTier2制限(20 reqs/min)に引っかかって起動できず、暫く待つ必要がある
    - 一時的にSlackとの接続が途切れたなどでまとめて再起動されると容易にひっかかる

**Comment by vorj** [comment]
- `exclude_archived` 付けたら緩和できないか？(@toru-fukaya)
- #26 も含めてユーザー・チャンネル情報は全体的にオンデマンドに切り替えたほうが良さそうな気がしている
    - チャンネル情報(チャンネルID→チャンネル名)は比較的安定しそうなのでキャッシュして良さそう
    - #26 で扱うユーザー名はチャンネル名に比べると安定しなさそうなのでいっそ都度取得でもいいかもしれない？RTMのイベントで拾えるならまぁキャッシュしてもええかぐらいの感じ

**Comment by toru-fukaya** [comment]
こっちで十分かも https://api.slack.com/methods/users.conversations

**Comment by vorj** [comment]
良さそう RTMでチャンネル追加イベントが拾えるならそれが来たときにそのチャンネルの情報だけ追加で拾えばいいですかね

**Comment by vorj** [comment]
改めてログを見直してみたところ、 `goodbye` イベントが似たようなタイミングで降ってきてるので、そのタイミングでTierの制限に引っかかってたっぽい？弊社Slackだと #28 で4台程度でも問題なく動作することを確認できています

**Comment by vorj** [comment]
とりあえず #28 で解決したっぽいので一旦閉じます、なんか問題があったらreopenしましょう
