### ISSUE TITLE
Privateチャンネル対応

### ISSUE THREAD

**Issue by vorj** [fixstars/sacana#30]
現行でも1行いじれば対応できる(技術的な難しさはない)が、それはそれとして対応していない。社内でprivateチャンネル用に運用する際に一発でできなくて困ってる人がいたのでなんとかすべき(私は自前で修正して導入していたが、全員にそれをやれというのは酷)

- 対応方法としては3通りくらいあって:
    1. ドキュメントで案内
        1. 自然言語で指示
        1. パッチの提示
    1. 普通にprivate channelも見にいけるようにする
- 上記を選ぶ前提として、そもそもなんでprivateにデフォで対応していないんだっけ？
    - 当初何かしらの制約や技術的課題があった？社内実装時のissueなどを参照する

**Comment by toru-fukaya** [comment]
特に理由は無かった気がするのでiiの普通にprivate channelも見に行けるようにするが良いと思う。

恐らくここにprivate channel追加するだけでいけるはず。
https://github.com/fixstars/sacana/blob/182f2c6c87c307533e6fadad987b66e7453604da/src/slack.rs#L335

**Comment by toru-fukaya** [comment]
あーそういえば #27 の対応前は全部のチャンネルが取得出来てしまって数が多すぎて面倒だったからとりあえずpublic限定にしたような気がする。
